openapi: 3.0.0
servers:
  - description: API for CU Neuron Capstone Project
    url: mockURL
info:
  description: This is the API for CU Neuron Capstone Project
  version: "1.0.0"
  title: CU Neuron Capstone Project
  contact:
    email: tikhamporntan@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: landing
    description: This api is for landing page. This page contains journeys, recently visited and search bar. It has two modes (undirected graph which shows associated paths and normal mode).
paths:
  /journeys:
    get:
      tags:
        - landing
      summary: Get journeys
      description: |
        API for getting journeys for user (Need to get userId from token)
        ```
        1. Get all journeys that user is involved
        SELECT (id, name) FROM journey WHERE id IN (SELECT journeyId FROM user_journey WHERE userId = 6330203521);

        2. Get all paths that in the journey
        SELECT * FROM path WHERE id IN (SELECT pathId FROM journey_path WHERE journeyId = 'j1'); ('j1' is example of journeyId from step 1)

        3. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 2)

        4. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 2)
        ```
      security:
        - bearerAuth: []
      responses:
        200:
          description: Get journeys successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                  journeys:
                    type: array
                    items:
                      $ref: "#/components/schemas/Journey"
                  relationships:
                    type: array
                    items:
                      $ref: "#/components/schemas/Relationship"
                example:
                  total: 2
                  journeys:
                    - id: "j1"
                      name: "English For Business"
                      progress: 50
                      paths:
                        total: 2
                        data:
                          - id: "p1"
                            name: "Grammar"
                            description: "Sentence Structure, Syntax and Punctuation"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                            tags:
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                            progress: 30
                          - id: "p2"
                            name: "Vocabulary"
                            description: "Word and Phrases"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                            tags:
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922512.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922513.svg"
                            progress: 50.5
                    - id: "j2"
                      name: "Communication Tips"
                      progress: 40
                      paths:
                        total: 1
                        data:
                          - id: "p5"
                            name: "Understanding Partner"
                            description: "How to understand your partner"
                            picture: "https://www.flaticon.com/svg/static/icons/svg/2922/2922513.svg"
                            tags:
                              - id: "c1"
                                name: "Daily Conversation"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922514.svg"
                              - id: "c2"
                                name: "Business"
                                icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922515.svg"
                            progress: 77
                  relationships:
                    - id: "p1"
                      neighbors: ["p2"]
                    - id: "p2"
                      neighbors: ["p1"]
                    - id: "p5"
                      neighbors: []
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /paths/:id:
    patch:
      tags:
        - landing
      summary: Update updatedAt colmun in user_path table (For displaying recently visited paths)
      description: |
        - Update updatedAt colmun in user_path table (Need to get userId from token). This path is used when user click on the path.
        ```
        UPDATE user_path SET updatedAt = CURRENT_TIMESTAMP WHERE userId = 6330203521 AND pathId = 'p1';

        If the path is not in the user_path table, it will insert the path into the table.
        INSERT INTO user_path (userId, pathId, progress) VALUES (6330203521, 'p1', 'Still learning');
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: id of path
          required: true
          schema:
            type: string
          example: "p1"
      responses:
        200:
          description: Update updatedAt colmun in user_path table successfully.
          content:
            application/json:
              example:
                message: Update updatedAt colmun in user_path table successfully.
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /paths/recently:
    get:
      tags:
        - landing
      summary: Get recently visited paths
      description: |
        API for getting recently visited paths for user (Need to get userId from token) Recently is defined as the updatedAt column in user_path table.
        ```
        1. Get all paths that user has visited
        SELECT * FROM path WHERE id IN (SELECT pathId FROM user_path WHERE userId = 6330203521 ORDER BY updatedAt DESC);

        2. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 1)

        3. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 1)
        ```
      security:
        - bearerAuth: []
      responses:
        200:
          description: Get recently visited paths successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Path"
                  relationships:
                    type: array
                    items:
                      $ref: "#/components/schemas/Relationship"
                example:
                  total: 1
                  data:
                    - id: "p1"
                      name: "Grammar"
                      description: "Sentence Structure, Syntax and Punctuation"
                      picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                      tags:
                        - id: "c1"
                          name: "Daily Conversation"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                        - id: "c2"
                          name: "Business"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                      progress: 88
                  relationships:
                    - id: "p1"
                      neighbors: []
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
  /search:
    get:
      tags:
        - landing
      summary: Search specific path
      description: |
        API for searching specific path.
        ```
        1. Get all paths that match the search query
        SELECT * FROM path WHERE name LIKE '%Grammar%';

        2. Get all tags that in the path
        SELECT * FROM tag WHERE id IN (SELECT tagId FROM path_tag WHERE pathId = 'p1'); ('p1' is example of pathId from step 1)

        3. Get all relationship between paths
        SELECT * FROM path_relationship WHERE pathId = 'p1'; ('p1' is example of pathId from step 1 or from step 3 itself)
        ```
      security:
        - bearerAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: search query
          required: true
        - name: depth
          in: query
          schema:
            type: integer
          description: depth of search result
          required: true
      responses:
        200:
          description: Search successfully.
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  total:
                    type: "integer"
                    description: total number of paths from the search result
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Path"
                  relationships:
                    type: array
                    items:
                      $ref: "#/components/schemas/Relationship"
                example:
                  total: 1
                  data:
                    - id: "p1"
                      name: "Grammar"
                      description: "Sentence Structure, Syntax and Punctuation"
                      picture: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
                      tags:
                        - id: "c1"
                          name: "Daily Conversation"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
                        - id: "c2"
                          name: "Business"
                          icon: "https://www.flaticon.com/svg/static/icons/svg/2922/2922511.svg"
                      progress: 10.5
                  relationships:
                    - id: "p1" # depth 0 (search result)
                      neighbors: ["p2"]
                    - id: "p2" # depth 1
                      neighbors: ["p1", "p3"]
                    - id: "p3" # depth 2
                      neighbors: ["p2", "p4"]
                    - id: "p4" # depth 3
                      neighbors: ["p3"] # only show path which is in the relationships
                    # p1 <--> p2 <--> p3 <--> p4
        400:
          description: Bad request
          content:
            application/json:
              example:
                message: Bad request. Please check the request payload.
        401:
          description: Unauthorized. Please login.
          content:
            application/json:
              example:
                message: Unauthorized. Please login.
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Journey:
      type: object
      properties:
        id:
          type: string
          example: "j1"
        name:
          type: string
          example: "English For Business"
        progress:
          type: integer
          example: 50
          description: progress of the journey (calculated from the number of paths that user has passed and show in percent)
        paths:
          type: object
          properties:
            total:
              type: integer
              example: 1
            data:
              type: array
              items:
                $ref: "#/components/schemas/Path"
    Path:
      type: object
      properties:
        id:
          type: string
          example: "p1"
        name:
          type: string
          example: "Grammar"
        description:
          type: string
          example: "Sentence Structure, Syntax and Punctuation"
        picture:
          type: string
          description: path's picture (if the path has no picture, it will be empty string)
          example: "https://www.flaticon.com/svg/static/icons/svg/2922/1112223.svg"
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
        progress:
          type: number
          format: float
    Tag:
      type: object
      properties:
        id:
          type: string
          example: "c1"
        name:
          type: string
          example: "Daily Conversation"
        icon:
          type: string
          example: "https://www.flaticon.com/svg/static/icons/svg/2922/2922510.svg"
    Relationship:
      description: Relationship between paths. For the search results, it will show the relationship between the searched path and the other paths in 3 depth.
      type: object
      properties:
        id:
          type: string
          example: "p1"
        neighbors:
          type: array
          description: array of associated path's id (Show only path's id which exists in the relationships)
          items:
            type: string
          example: ["p2", "p3", "p4"]
